var res = {
    BackGround1_png : "res/background1.png",
    BackGrounds_png : "res/background-start.png",
    BackGrounds2_png : "res/background-start2.png",
    StartA_png : "res/start.png",
    StartB_png : "res/start.png",
    Sushi_plist : "res/sushi.plist",
    SushiList_png : "res/sushi.png",
    Sushi_png : "res/sushi_c.png",
    Rabbit_png : "res/rabbit-index.png",
    Bone1_png : "res/bone1.png",
    Bone2_png : "res/bone2.png",
    Bone3_png : "res/bone3.png",
    Bone4_png : "res/bone4.png",
    Whole_png : "res/whole.png",
    Sushi_png : "res/sushi_c.png",
    Share_png : "res/share.png",
    Point_png : "res/point.png",
    Agian_png : "res/agian.png",
    RabbitH_png : "res/rabbit-hitted.png",
    start_music : "res/bg.mp3",
    Jump_music : "res/jump.mp3",
    Hit_music : "res/hit.wav",
    Over_music : "res/hit2.mp3",
    StartGame_music : "res/start.wav",
    Touch_music : "res/touch.wav",        
    rabbitlist:{
    	1 : "res/1.png",
    	2 : "res/2.png",
    	3 : "res/3.png",
    	4 : "res/4.png",
    	5: "res/5.png",
    	6 : "res/6.png",
    	7 : "res/7.png",
    	8: "res/8.png",
    	9 : "res/9.png",
    	10 : "res/10.png",
    	11 : "res/11.png",
    	12 : "res/12.png",
    	13 : "res/13.png",
    	14 : "res/14.png",
    	15 : "res/15.png",
    	16 : "res/16.png",
    	17 : "res/17.png",
    	18 : "res/18.png"
    },

};